name: peanut_api_test
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # UI
  gap: ^3.0.1
  google_fonts: ^8.0.0
  skeletonizer: ^2.1.0+1
  flutter_staggered_grid_view: ^0.7.0
  animated_read_more_text: ^0.0.6
  toastification: ^3.0.3
  pull_to_refresh: ^2.0.0
  flex_color_scheme: ^8.4.0
  pull_down_button: ^0.10.2
  # State Management
  riverpod_annotation: ^4.0.0
  hooks_riverpod: ^3.1.0
  flutter_hooks: ^0.21.2
  get_it: ^9.2.0
  go_router: ^17.0.1
  event_bus: ^2.0.1
  equatable: ^2.0.7
  # File/Storage
  shared_preferences: ^2.5.3
  # Network
  dio: ^5.9.0
  url_launcher: ^6.3.2
  # Utility
  recase: ^4.1.0
  fpdart: ^1.1.1
  collection: ^1.19.1
  intl: ^0.20.2
  form_builder_validators: ^11.2.0
  flutter_form_builder: ^10.2.0
  universal_image: ^1.0.11
  lucide_icons_flutter: ^3.1.9
  screwdriver: ^5.11.0
  shared_pref_annotation: ^1.0.1


  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.15
  custom_lint: ^0.8.1
  riverpod_lint: ^3.1.0
  riverpod_generator: ^4.0.0+1

flutter:
  uses-material-design: true

  assets:
    # - assets/svg/
    - assets/logo/
    # - assets/icons/
    # - assets/images/

flutter_gen:
  output: lib/_core/strings/
  line_length: 80
  integrations:
    flutter_svg: true
    lottie: true
